# Generated by Django 3.2 on 2021-07-30 02:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+(country Code)99999'. Up to 18 digits allowed.", regex='^\\+1?\\d{9,15}$')])),
                ('userType', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual')], default='', max_length=20)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyType', models.CharField(choices=[('Concrete Structure', 'Concrete Structure'), ('Steel Structure', 'Steel Structure'), ('Home Stay', 'Home Stay'), ('Land', 'Land'), ('Flat', 'Flat'), ('House', 'House')], max_length=50)),
                ('Category', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], max_length=30)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Size', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Rooms', models.IntegerField()),
                ('FinalCost', models.IntegerField()),
                ('MiddleCost', models.IntegerField()),
                ('InitialCost', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Price', models.IntegerField()),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('ServiceType', models.CharField(choices=[('Electrician', 'Electrician'), ('Architecture', 'Architecture'), ('Event management1', 'Event management1'), ('new category for testing T5231', 'new category for testing T5231'), ('Adminstration..', 'Adminstration..'), ('Supervision', 'Supervision'), ('Plumbing', 'Plumbing')], max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20)),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('PropertyType', models.CharField(choices=[('Concrete Structure', 'Concrete Structure'), ('Steel Structure', 'Steel Structure'), ('Home Stay', 'Home Stay'), ('Land', 'Land'), ('Flat', 'Flat'), ('House', 'House')], default='', max_length=50)),
                ('SubCategory', models.CharField(choices=[('Flat/House/Apartment', 'Flat/House/Apartment'), ('Trees Work', 'Trees Work'), ('Gardening', 'Gardening'), ('Public', 'Public'), ('Private', 'Private'), ('In Dispute', 'In Dispute'), ('Farm Land', 'Farm Land'), ('Non-Cultivated', 'Non-Cultivated'), ('Cultivated', 'Cultivated'), ('Partially Furnished', 'Partially Furnished'), ('Fully Furnished', 'Fully Furnished')], default='', max_length=50)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Size', models.IntegerField(default=0)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], default='', max_length=20)),
                ('Price', models.IntegerField()),
                ('PriceConditions', models.CharField(default='', max_length=150)),
                ('Deposit', models.IntegerField(blank=True, null=True)),
                ('AgentCommision', models.IntegerField(blank=True, null=True)),
                ('BuildYear', models.IntegerField()),
                ('Rooms', models.IntegerField()),
                ('Garages', models.IntegerField()),
                ('Bathroom', models.IntegerField()),
                ('CarSpaces', models.IntegerField()),
                ('FullyFurnished', models.BooleanField(default=0)),
                ('IndoorFeaturs', models.CharField(max_length=500)),
                ('OutdoorFeatures', models.CharField(max_length=500)),
                ('EcoFeatures', models.CharField(max_length=500)),
                ('OtherFeatures', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(default='', max_length=20)),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(choices=[('Test Cate', 'Test Cate'), ('Cement', 'Cement'), ('Tiles', 'Tiles'), ('Sand', 'Sand'), ('Gravel', 'Gravel'), ('Iron', 'Iron'), ('Limestone', 'Limestone')], max_length=50)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Weight', models.CharField(choices=[('KG', 'KG'), ('Pound', 'Pound'), ('Tonne', 'Tonne'), ('Grams', 'Grams'), ('Milligrams', 'Milligrams'), ('Meters', 'Meters'), ('Square Meters', 'Square Meters'), ('Centimeters', 'Centimeters'), ('Inches', 'Inches'), ('Millimeters', 'Millimeters')], max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('projectId', models.IntegerField()),
                ('image', models.FileField(upload_to='Images')),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='documents')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Price', models.IntegerField()),
                ('EquipmentType', models.CharField(choices=[('Tractor', 'Tractor'), ('JCB', 'JCB'), ('Cutter', 'Cutter'), ('TTT', 'TTT')], max_length=50)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Hire', models.CharField(choices=[('Hire', 'Hire'), ('Buy', 'Buy')], max_length=30)),
                ('Status', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
