# Generated by Django 3.2 on 2021-08-06 04:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Price', models.IntegerField()),
                ('EquipmentType', models.CharField(choices=[('Tractor', 'Tractor'), ('JCB', 'JCB'), ('Cutter', 'Cutter'), ('TTT', 'TTT')], max_length=50)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Hire', models.CharField(choices=[('Hire', 'Hire'), ('Buy', 'Buy')], max_length=30)),
                ('Status', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=30)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.FileField(blank=True, null=True, upload_to='Images')),
                ('image1Verify', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20)),
                ('Title', models.CharField(default='', max_length=50)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Rooms', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Bills', models.BooleanField(default=0)),
                ('Term', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('1 Year', '1 Year'), ('1.5 Years', '1.5 Years'), ('2 Years', '2 Years'), ('2+ Year', '2+ Year')], max_length=90)),
                ('Short', models.BooleanField()),
                ('Toilet', models.BooleanField()),
                ('Furnishing', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Garage', models.BooleanField()),
                ('Garden', models.BooleanField()),
                ('Balcony', models.BooleanField()),
                ('LivingRoom', models.BooleanField()),
                ('Broadband', models.BooleanField()),
                ('MaxAge', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Couple', 'Couple'), ('Male', 'Male'), ('Either Male or Female', 'Either Male or Female'), ('Female', 'Female')], max_length=50)),
                ('Occupation', models.CharField(choices=[('Students', 'Students'), ('Professionals', 'Professionals')], max_length=40)),
                ('Smoker', models.BooleanField()),
                ('Pets', models.BooleanField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.FileField(blank=True, null=True, upload_to='Images')),
                ('image1Verify', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(default='', max_length=20)),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(choices=[('Test Cate', 'Test Cate'), ('Cement', 'Cement'), ('Tiles', 'Tiles'), ('Sand', 'Sand'), ('Gravel', 'Gravel'), ('Iron', 'Iron'), ('Limestone', 'Limestone')], max_length=50)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Weight', models.CharField(choices=[('KG', 'KG'), ('Pound', 'Pound'), ('Tonne', 'Tonne'), ('Grams', 'Grams'), ('Milligrams', 'Milligrams'), ('Meters', 'Meters'), ('Square Meters', 'Square Meters'), ('Centimeters', 'Centimeters'), ('Inches', 'Inches'), ('Millimeters', 'Millimeters')], max_length=80)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.FileField(blank=True, null=True, upload_to='Images')),
                ('image1Verify', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20)),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('PropertyType', models.CharField(choices=[('Concrete Structure', 'Concrete Structure'), ('Steel Structure', 'Steel Structure'), ('Home Stay', 'Home Stay'), ('Land', 'Land'), ('Flat', 'Flat'), ('House', 'House')], default='', max_length=50)),
                ('SubCategory', models.CharField(choices=[('Flat/House/Apartment', 'Flat/House/Apartment'), ('Trees Work', 'Trees Work'), ('Gardening', 'Gardening'), ('Public', 'Public'), ('Private', 'Private'), ('In Dispute', 'In Dispute'), ('Farm Land', 'Farm Land'), ('Non-Cultivated', 'Non-Cultivated'), ('Cultivated', 'Cultivated'), ('Partially Furnished', 'Partially Furnished'), ('Fully Furnished', 'Fully Furnished')], default='', max_length=50)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Size', models.IntegerField(default=0)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], default='', max_length=20)),
                ('Price', models.IntegerField()),
                ('PriceConditions', models.CharField(default='', max_length=150)),
                ('Deposit', models.IntegerField(blank=True, null=True)),
                ('AgentCommision', models.IntegerField(blank=True, null=True)),
                ('BuildYear', models.IntegerField()),
                ('Rooms', models.IntegerField()),
                ('Garages', models.IntegerField()),
                ('Bathroom', models.IntegerField()),
                ('CarSpaces', models.IntegerField()),
                ('FullyFurnished', models.BooleanField(blank=True, null=True)),
                ('IndoorFeaturs', models.CharField(max_length=500)),
                ('OutdoorFeatures', models.CharField(max_length=500)),
                ('EcoFeatures', models.CharField(max_length=500)),
                ('OtherFeatures', models.CharField(max_length=500)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.FileField(blank=True, null=True, upload_to='Images')),
                ('image1Verify', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Price', models.IntegerField()),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('ServiceType', models.CharField(choices=[('Electrician', 'Electrician'), ('Architecture', 'Architecture'), ('Event management1', 'Event management1'), ('new category for testing T5231', 'new category for testing T5231'), ('Adminstration..', 'Adminstration..'), ('Supervision', 'Supervision'), ('Plumbing', 'Plumbing')], max_length=80)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.FileField(blank=True, null=True, upload_to='Images')),
                ('image1Verify', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyType', models.CharField(choices=[('Concrete Structure', 'Concrete Structure'), ('Steel Structure', 'Steel Structure'), ('Home Stay', 'Home Stay'), ('Land', 'Land'), ('Flat', 'Flat'), ('House', 'House')], max_length=50)),
                ('Category', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], max_length=30)),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Size', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Rooms', models.IntegerField()),
                ('FinalCost', models.IntegerField()),
                ('MiddleCost', models.IntegerField()),
                ('InitialCost', models.IntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('image1', models.FileField(blank=True, null=True, upload_to='Images')),
                ('image1Verify', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+(country Code)99999'. Up to 18 digits allowed.", regex='^\\+1?\\d{9,15}$')])),
                ('userType', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual')], default='', max_length=20)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Verified', models.BooleanField(blank=True, null=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.structure')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Verified', models.BooleanField(blank=True, null=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyIMage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Verified', models.BooleanField(blank=True, null=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Verified', models.BooleanField(blank=True, null=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
            ],
        ),
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Verified', models.BooleanField(blank=True, null=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='documents')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Verified', models.BooleanField(blank=True, null=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipment')),
            ],
        ),
    ]
