# Generated by Django 3.2 on 2021-08-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_property_fullyfurnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='material',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='structure',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='verified',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(default='', max_length=20)),
                ('Type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20)),
                ('Title', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Rooms', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Currency', models.CharField(choices=[('₦ NGN', '₦ NGN'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('€ EUR', '€ EUR')], max_length=20)),
                ('Bills', models.BooleanField(default=0)),
                ('Term', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('1 Year', '1 Year'), ('1.5 Years', '1.5 Years'), ('2 Years', '2 Years'), ('2+ Year', '2+ Year')], max_length=90)),
                ('Short', models.BooleanField()),
                ('Toilet', models.BooleanField()),
                ('Furnishing', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Garage', models.BooleanField()),
                ('Garden', models.BooleanField()),
                ('Balcony', models.BooleanField()),
                ('LivingRoom', models.BooleanField()),
                ('Broadband', models.BooleanField()),
                ('MaxAge', models.IntegerField()),
                ('Occupation', models.CharField(choices=[('Students', 'Students'), ('Professionals', 'Professionals')], max_length=40)),
                ('Smoker', models.BooleanField()),
                ('Pets', models.BooleanField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
