# Generated by Django 3.2 on 2021-08-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210801_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Gender',
            field=models.CharField(choices=[('Couple', 'Couple'), ('Male', 'Male'), ('Either Male or Female', 'Either Male or Female'), ('Female', 'Female')], default='Male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='Location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
