# Generated by Django 3.2 on 2021-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_smtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
