# Generated by Django 3.2 on 2021-08-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210802_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='Item',
        ),
    ]
